import express from "express";
import { addEvent, get_all_Event, get_event_by_id, updateEvent, deleteEvent,get_Event_by_user } from "../controller/eventController.js";
import {verifyToken} from "../middleware/authMiddleware.js";
const router = express.Router();
router.post("/addEvent", verifyToken, addEvent);
router.get("/allEvent", get_all_Event);
router.get("/Event/:id", get_event_by_id);
router.put("/update_event/:id", updateEvent);
router.delete("/dell_event/:id", deleteEvent);
router.get("/user_event",get_Event_by_user);
export default router;